const cities = require('./cities/cities.service.js');
const countries = require('./countries/countries.service.js');
const leagues = require('./leagues/leagues.service.js');
const matches = require('./matches/matches.service.js');
const playerCategories = require('./player_categories/player_categories.service.js');
const playersStatsWeeklyPoints = require('./players_stats_weekly_points/players_stats_weekly_points.service.js');
const playersWeeklyPoint = require('./players_weekly_point/players_weekly_point.service.js');
const playersWeeklyTransferValue = require('./players_weekly_transfer_value/players_weekly_transfer_value.service.js');
const players = require('./players/players.service.js');
const seasons = require('./seasons/seasons.service.js');
const settings = require('./settings/settings.service.js');
const staffCategories = require('./staff_categories/staff_categories.service.js');
const staffTypes = require('./staff_types/staff_types.service.js');
const staffs = require('./staffs/staffs.service.js');
const statsPoints = require('./stats_points/stats_points.service.js');
const teamFormations = require('./team_formations/team_formations.service.js');
const teams = require('./teams/teams.service.js');
const trainings = require('./trainings/trainings.service.js');
const userTeamsPlayersStatsWeeklyPoints = require('./user_teams_players_stats_weekly_points/user_teams_players_stats_weekly_points.service.js');
const userTeamsPlayersWeeklyPoint = require('./user_teams_players_weekly_point/user_teams_players_weekly_point.service.js');
const userTeamsSquad = require('./user_teams_squad/user_teams_squad.service.js');
const userTeamsStaffs = require('./user_teams_staffs/user_teams_staffs.service.js');
const userTeamsWeeklyFinances = require('./user_teams_weekly_finances/user_teams_weekly_finances.service.js');
const userTeamsWeeklyFormation = require('./user_teams_weekly_formation/user_teams_weekly_formation.service.js');
const userTeamsWeeklyLineupSwaps = require('./user_teams_weekly_lineup_swaps/user_teams_weekly_lineup_swaps.service.js');
const userTeamsWeeklyLineup = require('./user_teams_weekly_lineup/user_teams_weekly_lineup.service.js');
const userTeamsWeeklyPoint = require('./user_teams_weekly_point/user_teams_weekly_point.service.js');
const userTeamsWeeklyTrainings = require('./user_teams_weekly_trainings/user_teams_weekly_trainings.service.js');
const userTeamsWeeklyTransfers = require('./user_teams_weekly_transfers/user_teams_weekly_transfers.service.js');
const userTeams = require('./user_teams/user_teams.service.js');
const wfmGameweeks = require('./wfm_gameweeks/wfm_gameweeks.service.js');
// eslint-disable-next-line no-unused-vars
module.exports = function (app) {
  app.configure(cities);
  app.configure(countries);
  app.configure(leagues);
  app.configure(matches);
  app.configure(playerCategories);
  app.configure(playersStatsWeeklyPoints);
  app.configure(playersWeeklyPoint);
  app.configure(playersWeeklyTransferValue);
  app.configure(players);
  app.configure(seasons);
  app.configure(settings);
  app.configure(staffCategories);
  app.configure(staffTypes);
  app.configure(staffs);
  app.configure(statsPoints);
  app.configure(teamFormations);
  app.configure(teams);
  app.configure(trainings);
  app.configure(userTeamsPlayersStatsWeeklyPoints);
  app.configure(userTeamsPlayersWeeklyPoint);
  app.configure(userTeamsSquad);
  app.configure(userTeamsStaffs);
  app.configure(userTeamsWeeklyFinances);
  app.configure(userTeamsWeeklyFormation);
  app.configure(userTeamsWeeklyLineupSwaps);
  app.configure(userTeamsWeeklyLineup);
  app.configure(userTeamsWeeklyPoint);
  app.configure(userTeamsWeeklyTrainings);
  app.configure(userTeamsWeeklyTransfers);
  app.configure(userTeams);
  app.configure(wfmGameweeks);
};
